backend:
  name: git-gateway
  branch: main

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    format: "json"
    files:
      - file: "source/content/home.json"
        label: "Homepage Hero"
        name: "hero"
        fields:
          - { label: "Hero Title",    name: "heroTitle",    widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Primary CTA Text", name: "cta1Text",  widget: "string", default: "Get Quote" }
          - { label: "Primary CTA Link", name: "cta1Href",  widget: "string", default: "contact.html" }
          - { label: "Secondary CTA Text", name: "cta2Text", widget: "string", default: "View Products" }
          - { label: "Secondary CTA Link", name: "cta2Href", widget: "string", default: "products.html" }
          - { label: "Hero Background", name: "heroImage",  widget: "image",  default: "/images/hero/baiyun-line.jpg" }
